name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Test Dependencies
        run: |
          pip install -r test-requirements.txt
      - name: Run Tests
        run: |
          pytest -v -vrxs
